#!/bin/bash
# Author: Ankit Sharma
# Description: this script will help you to create and Manage users
# Date: 1-7-2020
echo "please provide username"

read u 

grep -q $u /etc/passwd

if [ $? -eq 0 ]
	then
	echo Eroor -- User $u is Already Exist
	echo  Please Choose Another Useraname
	echo 
	exit 0 
	fi

echo " Please Provide user description" 

read desc 
echo 

echo "please enter your password"
read pass

echo "do you want to specify UID optional ( y/n ) ?"
read ud
echo

	if [ $ud == y ]
		then
		echo "please choose uid"
		read uid
			grep -q $uid /etc/passwd
				if [ $? -eq 0 ]
					then
					echo $uid already exist 
					echo Choose anohter id
					exit 0
						
				else
				useradd $u -c "$d" -u $uid -p $pass
				echo  $u account created
				echo
				fi
	elif [ $ud == n ]
	then
	echo "no worries we will assign uid" 
	echo useradd $u -c "$d" -p $pass
	echo user $u created 
	fi	

